version: '3.1'

services:

  db-excel:
    image: mysql:latest
    # command: --mysql-native-password=ON
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_POST}"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - "${ADMINER_HOST_PORT}:${ADMINER_CONTAINER_PORT}"
